CREATE TABLE CLIENTI (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cognome TEXT NOT NULL,
    note TEXT,
    creata_il TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);