CREATE TABLE servizi(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    prezzo NUMERIC(10, 2) NOT NULL CHECK (prezzo >= 0),
    attivo BOOLEAN NOT NULL DEFAULT TRUE
);